### PR TITLE
Fix: Some ui quick wins

### PR DESCRIPTION
**Pull request by gyandeeps**
* Sidebar scroll to only show when needed.
    * When scrollbar comes up only show around collapsible areas.
* Use padding and not height for author name. It looks nice and centered.
* Only show bottom footer if their is information to display.
    * For success type banner, hide it after 2 seconds.
    * For all other types, show until fixed.

### CODE REVIEW

**Comment by ritz078** [comment]
The footer still remains.. It just doesn't show any content and only the border is removed. I don't think there is a need to remove it. I wanted it as a notification are which is always visible.

**Comment by ritz078** [comment]
Could you have a look at scrollbar issue ? I think it is mainly due to using `calc` in CSS.

**Comment by gyandeeps** [comment]
> could you check the current master for scroll issue ?

its better than before as now you can actually scroll. but now we have double scrollbars on both sections.

> The footer still remains.. It just doesn't show any content and only the border is removed. I don't think there is a need to remove it. I wanted it as a notification are which is always visible.

If you try running my branch then you will see that footer is not their..

**Comment by ritz078** [comment]
I guess the scroll fix should solve the bottleneck for mobile compatibility ?

**Comment by ritz078** [comment]
@gyandeeps Would you like to be added to the org ?

**Comment by gyandeeps** [comment]
Sure why nt... I can help in certain areas.... Thanks

**Comment by ritz078** [comment]
Invite sent.

**Comment by ritz078** [comment]
@gyandeeps Can you review the PR I have tagged you in ?

**Pull request merged**
