### PR TITLE
New: PWA support with manifest

### PR DESCRIPTION
**Pull request by gyandeeps**
Make Transform a PWA. 😄

### CODE REVIEW

**Comment by ritz078** [comment]
Thanks for your contribution. The icons should be flat. If you are trying transparent background, then make the icons dark. Here is the [original icon](https://thenounproject.com/search/?q=transform&i=920800)

**Comment by gyandeeps** [comment]
Yeah, i did not have the correct icons. I dont know if we really want a transparent background. I will let you make that decision.

**Comment by gyandeeps** [comment]
included in #30

**Comment by ritz078** [comment]
I would prefer on the dark background. white icon on `#424242`

**Pull request closed without merging**
